(ns boot.generate.ns
  (:require [boot.new.templates :as tmpl]))

(defn generate
  "Generate a new namespace relative to the prefix."
  [prefix ns-name]
  (gen-file/generate prefix ns-name (str "(ns " ns-name "\n  \"Generated by Boot\")\n")))
